[title]
font.family = "Times New Roman"
font.size = 60
font.weight = "bold"
font.slant = "roman"
font.underline = 0
font.overstrike = 0
foreground = "#ffff00"
background = "#000000"
borderwidth = 0
anchor = "w"
padding.x = 20
padding.y = 0
grid.padding.x = 0
grid.padding.y = 0
grid.sticky = "ew"

[time]
font.family = "Calibri"
font.size = 30
font.weight = "normal"
font.slant = "roman"
font.underline = 0
font.overstrike = 0
foreground = "#ffff00"
background = "#000000"
borderwidth = 0
anchor = "e"
padding.x = 20
grid.padding.x = 0
grid.padding.y = 0
grid.sticky = "nsew"

[header]
font.family = "Calibri"
font.size = 40
font.weight = "normal"
font.slant = "roman"
font.underline = 0
font.overstrike = 0
foreground = "#ffffff"
background = "#0000ff"
borderwidth = 0
anchor = "center"
grid.padding.x = 0
grid.padding.y = 0
grid.sticky = "nsew"

[body]
font.family = "Times New Roman"
font.size = 30
font.weight = "bold"
font.slant = "roman"
font.underline = 0
font.overstrike = 0
foreground = "#ffffff"
background = "#000000"
borderwidth = 0
anchor = "center"
grid.padding.x = 0
grid.padding.y = 3
grid.sticky = "nsew"

[body2]
font.family = "Times New Roman"
font.size = 30
font.weight = "bold"
font.slant = "roman"
font.underline = 0
font.overstrike = 0
foreground = "#ffffff"
background = "#000000"
borderwidth = 0
anchor = "center"
grid.padding.x = 0
grid.padding.y = 3
grid.sticky = "nsew"

[error]
font.family = "Lato"
font.size = 80
font.weight = "bold"
font.slant = "roman"
font.underline = 0
font.overstrike = 0
foreground = "#ff0000"
background = "#ffff00"
borderwidth = 0
anchor = "center"
grid.padding.x = 0
grid.padding.y = 0
grid.sticky = "nsew"

[icons]
airline_logo.size = 50